### PR TITLE
Add icon gitlab

### PR DESCRIPTION
**Pull request by biblesyme**
Add icon gitlab for pipeline usage

### CODE REVIEW

**Comment by vincent99** [comment]
Can you sort it at the bottom with the other company logos and set the setId so it doesn't change a line for every icon ; or ask @lvuch to add it

**Comment by biblesyme** [comment]
Ok, I will ask @lvuch for help. I moved it to bottom, but I found I can't avoid changing the `order` number( Every icon's order number increased, but the relative order keep the same). By the way, the setId always is `1` when I download it from IcoMoon.

**Comment by lvuch** [comment]
https://github.com/rancher/icons/pull/17 @biblesyme @vincent99 let me know if this fixes the issue

**Comment by vincent99** [comment]
Somewhat, I don't know why the setIds all change for no reason but #17 preserves the order...

**Pull request closed without merging**
